### DISCUSSION TITLE
Formatting Standard(s)?

### DISCUSSION THREAD

**Discussion by ubahmapk** [stanfrbd/cyberbro#67] [General]
What python formatting/lint settings do you use? Would you consider adding the config (e.g. `.ruff.toml`) to the repo?

My current, global, ruff settings keep making large changes to the code base here, which tend to add noise to PRs. I'd be happy to make changes within my project folder to keep in line with whatever standard(s) you want to adhere to.

As a starting point, my current ruff config looks like this (I probably use too many, but....):

```
[lint]
exclude = ["tests/**"]
select = [
    "E",   # Pycodestyle errors
    "F",   # Pyflakes
    "W",   # Pywicked
    "B",   # Flake8-bugbear
    "C4",  # Flake8-comprehensions
    "I",   # Isort
    "N",   # PEP8-Naming
    "PGH", # Flake8-pygments
    "PTH", # Flake8-pytest-helper
    "RET", # Flake8-return
    "RUF", # Ruff-specific rules
    "SIM", # Flake8-simplify
    "UP",  # Flake8-pyupgrade
    "YTT", # Flake8-2020
]
```

**Comment by stanfrbd** [comment]
@ubahmapk I don't use any formatting now (it's a shame!). 

Please feel free to add it, and thanks again!

**Comment by stanfrbd** [comment]
@ubahmapk What did you define in terms of line limits? 88 or more? 
I'm starting to reformat :)

**Reply by ubahmapk** [reply]
I argue with myself all the time on what the line length should be.

I've had it as high as 120 (nice, wide monitors) and as low as 88.

Seems to me the traditional limit of 79 is too narrow, but maybe that's just me. :-)

**Reply by stanfrbd** [reply]
I added this in #71 and this wiki page

https://github.com/stanfrbd/cyberbro/wiki/Coding-Style

Feel free to edit it if you want, I hope I did it well :)

I think it can be awesome to work on the `pre-commit` hook (which already exists)

**Reply by ubahmapk** [reply]
Awesome!

I actually already have ruff lint and formatting running on a local pre-commit hook for this. 

```
exclude: "^.*/(tests/)"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff
        types_or: [python, pyi]
        args: [--fix, --config=.ruff.toml]
      # Run the linter.
      - id: ruff-format
        types_or: [python, pyi]
        args: [--config=.ruff.toml]
```
